module.exports = {
    // Smelting time per item in ticks (standard is 200 ticks = 10 seconds)
    SMELTING_TIME : 200,
    // Fuel values in ticks (20 ticks = 1 second)
    // These are standard Minecraft fuel burn times
    FUEL_VALUES : {
        'lava_bucket': 20000,  // 1000 seconds
        'coal_block': 16000,   // 800 seconds
        'dried_kelp_block': 4000, // 200 seconds
        'blaze_rod': 2400,     // 120 seconds
        'coal': 1600,          // 80 seconds
        'charcoal': 1600,      // 80 seconds
        'boat': 1200,          // 60 seconds (any boat type)
        'oak_boat': 1200,
        'spruce_boat': 1200,
        'birch_boat': 1200,
        'jungle_boat': 1200,
        'acacia_boat': 1200,
        'dark_oak_boat': 1200,
        'mangrove_boat': 1200,
        'cherry_boat': 1200,
        'bamboo_raft': 1200,
        'chest_boat': 1200,    // Any chest boat
        'scaffolding': 400,     // 20 seconds
        'bamboo': 50,          // 2.5 seconds
        'log': 300,            // 15 seconds (any log type)
        'oak_log': 300,
        'spruce_log': 300,
        'birch_log': 300,
        'jungle_log': 300,
        'acacia_log': 300,
        'dark_oak_log': 300,
        'mangrove_log': 300,
        'cherry_log': 300,
        'crimson_stem': 300,
        'warped_stem': 300,
        'stripped_oak_log': 300,
        'stripped_spruce_log': 300,
        'stripped_birch_log': 300,
        'stripped_jungle_log': 300,
        'stripped_acacia_log': 300,
        'stripped_dark_oak_log': 300,
        'stripped_mangrove_log': 300,
        'stripped_cherry_log': 300,
        'stripped_crimson_stem': 300,
        'stripped_warped_stem': 300,
        'wood': 300,           // Any wood type
        'oak_wood': 300,
        'spruce_wood': 300,
        'birch_wood': 300,
        'jungle_wood': 300,
        'acacia_wood': 300,
        'dark_oak_wood': 300,
        'mangrove_wood': 300,
        'cherry_wood': 300,
        'crimson_hyphae': 300,
        'warped_hyphae': 300,
        'planks': 300,         // Any planks
        'oak_planks': 300,
        'spruce_planks': 300,
        'birch_planks': 300,
        'jungle_planks': 300,
        'acacia_planks': 300,
        'dark_oak_planks': 300,
        'mangrove_planks': 300,
        'cherry_planks': 300,
        'crimson_planks': 300,
        'warped_planks': 300,
        'bamboo_planks': 300,
        'bamboo_mosaic': 300,
        'wooden_slab': 150,    // Any wooden slab (7.5 seconds)
        'oak_slab': 150,
        'spruce_slab': 150,
        'birch_slab': 150,
        'jungle_slab': 150,
        'acacia_slab': 150,
        'dark_oak_slab': 150,
        'mangrove_slab': 150,
        'cherry_slab': 150,
        'crimson_slab': 150,
        'warped_slab': 150,
        'bamboo_slab': 150,
        'bamboo_mosaic_slab': 150,
        'fence': 300,          // Any fence
        'oak_fence': 300,
        'spruce_fence': 300,
        'birch_fence': 300,
        'jungle_fence': 300,
        'acacia_fence': 300,
        'dark_oak_fence': 300,
        'mangrove_fence': 300,
        'cherry_fence': 300,
        'crimson_fence': 300,
        'warped_fence': 300,
        'bamboo_fence': 300,
        'fence_gate': 300,     // Any fence gate
        'oak_fence_gate': 300,
        'spruce_fence_gate': 300,
        'birch_fence_gate': 300,
        'jungle_fence_gate': 300,
        'acacia_fence_gate': 300,
        'dark_oak_fence_gate': 300,
        'mangrove_fence_gate': 300,
        'cherry_fence_gate': 300,
        'crimson_fence_gate': 300,
        'warped_fence_gate': 300,
        'bamboo_fence_gate': 300,
        'stairs': 300,         // Any wooden stairs
        'oak_stairs': 300,
        'spruce_stairs': 300,
        'birch_stairs': 300,
        'jungle_stairs': 300,
        'acacia_stairs': 300,
        'dark_oak_stairs': 300,
        'mangrove_stairs': 300,
        'cherry_stairs': 300,
        'crimson_stairs': 300,
        'warped_stairs': 300,
        'bamboo_stairs': 300,
        'bamboo_mosaic_stairs': 300,
        'trapdoor': 300,       // Any wooden trapdoor
        'oak_trapdoor': 300,
        'spruce_trapdoor': 300,
        'birch_trapdoor': 300,
        'jungle_trapdoor': 300,
        'acacia_trapdoor': 300,
        'dark_oak_trapdoor': 300,
        'mangrove_trapdoor': 300,
        'cherry_trapdoor': 300,
        'crimson_trapdoor': 300,
        'warped_trapdoor': 300,
        'bamboo_trapdoor': 300,
        'crafting_table': 300,
        'bookshelf': 300,
        'chest': 300,
        'trapped_chest': 300,
        'daylight_detector': 300,
        'jukebox': 300,
        'note_block': 300,
        'banner': 300,          // Any banner
        'bow': 300,
        'fishing_rod': 300,
        'ladder': 300,
        'sign': 200,           // Any sign (10 seconds)
        'oak_sign': 200,
        'spruce_sign': 200,
        'birch_sign': 200,
        'jungle_sign': 200,
        'acacia_sign': 200,
        'dark_oak_sign': 200,
        'mangrove_sign': 200,
        'cherry_sign': 200,
        'crimson_sign': 200,
        'warped_sign': 200,
        'bamboo_sign': 200,
        'hanging_sign': 800,    // Any hanging sign (40 seconds)
        'oak_hanging_sign': 800,
        'spruce_hanging_sign': 800,
        'birch_hanging_sign': 800,
        'jungle_hanging_sign': 800,
        'acacia_hanging_sign': 800,
        'dark_oak_hanging_sign': 800,
        'mangrove_hanging_sign': 800,
        'cherry_hanging_sign': 800,
        'crimson_hanging_sign': 800,
        'warped_hanging_sign': 800,
        'bamboo_hanging_sign': 800,
        'wooden_shovel': 200,   // Any wooden tool (10 seconds)
        'wooden_pickaxe': 200,
        'wooden_axe': 200,
        'wooden_hoe': 200,
        'wooden_sword': 200,
        'stick': 100,          // 5 seconds
        'sapling': 100,        // Any sapling
        'oak_sapling': 100,
        'spruce_sapling': 100,
        'birch_sapling': 100,
        'jungle_sapling': 100,
        'acacia_sapling': 100,
        'dark_oak_sapling': 100,
        'mangrove_propagule': 100,
        'cherry_sapling': 100,
        'azalea': 100,
        'flowering_azalea': 100,
        'bowl': 100,
        'wool': 100,           // Any color wool
        'carpet': 67,          // Any carpet (3.35 seconds)
        'dried_kelp': 200,     // 10 seconds
        'crossbow': 300,
        'smithing_table': 300,
        'fletching_table': 300,
        'cartography_table': 300,
        'loom': 300,
        'barrel': 300,
        'smoker': 300,
        'blast_furnace': 300,
        'composter': 300,
        'lectern': 300,
        'bee_nest': 300,
        'beehive': 300
    },
    SMELTABLE_ITEMS : [
        'raw_iron', 'raw_gold', 'raw_copper',
        'iron_ore', 'gold_ore', 'copper_ore', 'ancient_debris',
        'sand', 'red_sand', 'cobblestone', 'stone', 'clay_ball', 'netherrack',
        'clay', 'cactus', 'log', 'wood', 'sponge', 'wet_sponge',
        'kelp', 'bamboo', 'potato', 'raw_beef', 'raw_chicken',
        'raw_cod', 'raw_mutton', 'raw_porkchop', 'raw_rabbit', 'raw_salmon',
        'chorus_fruit', 'sea_pickle'
    ],
    // Map of input to output for smelting
    SMELTING_RESULTS : {
        'raw_iron': 'iron_ingot',
        'iron_ore': 'iron_ingot',
        'deepslate_iron_ore': 'iron_ingot',
        'raw_gold': 'gold_ingot',
        'gold_ore': 'gold_ingot',
        'deepslate_gold_ore': 'gold_ingot',
        'nether_gold_ore': 'gold_nugget',
        'raw_copper': 'copper_ingot',
        'copper_ore': 'copper_ingot',
        'deepslate_copper_ore': 'copper_ingot',
        'ancient_debris': 'netherite_scrap',
        'sand': 'glass',
        'red_sand': 'glass',
        'cobblestone': 'stone',
        'stone': 'smooth_stone',
        'clay_ball': 'brick',
        'clay': 'terracotta',
        'netherrack': 'nether_brick',
        'cactus': 'green_dye',
        'kelp': 'dried_kelp',
        'potato': 'baked_potato',
        'raw_beef': 'cooked_beef',
        'raw_chicken': 'cooked_chicken',
        'raw_cod': 'cooked_cod',
        'raw_mutton': 'cooked_mutton',
        'raw_porkchop': 'cooked_porkchop',
        'raw_rabbit': 'cooked_rabbit',
        'raw_salmon': 'cooked_salmon',
        'chorus_fruit': 'popped_chorus_fruit',
        'wet_sponge': 'sponge',
        'sea_pickle': 'lime_dye'
    }
}